/* Auto-generated by convert_icons.py — DO NOT EDIT */

#ifndef __AI_WATCH_ICONS_H
#define __AI_WATCH_ICONS_H

#include <lvgl/lvgl.h>

#define AI_WATCH_ICON_TIERS  5

extern const lv_image_dsc_t icon_exercise_t0;
extern const lv_image_dsc_t icon_exercise_t1;
extern const lv_image_dsc_t icon_exercise_t2;
extern const lv_image_dsc_t icon_exercise_t3;
extern const lv_image_dsc_t icon_exercise_t4;

extern const lv_image_dsc_t icon_timer_t0;
extern const lv_image_dsc_t icon_timer_t1;
extern const lv_image_dsc_t icon_timer_t2;
extern const lv_image_dsc_t icon_timer_t3;
extern const lv_image_dsc_t icon_timer_t4;

extern const lv_image_dsc_t icon_reminder_t0;
extern const lv_image_dsc_t icon_reminder_t1;
extern const lv_image_dsc_t icon_reminder_t2;
extern const lv_image_dsc_t icon_reminder_t3;
extern const lv_image_dsc_t icon_reminder_t4;

extern const lv_image_dsc_t icon_settings_t0;
extern const lv_image_dsc_t icon_settings_t1;
extern const lv_image_dsc_t icon_settings_t2;
extern const lv_image_dsc_t icon_settings_t3;
extern const lv_image_dsc_t icon_settings_t4;

extern const lv_image_dsc_t icon_heart_rate_t0;
extern const lv_image_dsc_t icon_heart_rate_t1;
extern const lv_image_dsc_t icon_heart_rate_t2;
extern const lv_image_dsc_t icon_heart_rate_t3;
extern const lv_image_dsc_t icon_heart_rate_t4;

extern const lv_image_dsc_t icon_blood_oxygen_t0;
extern const lv_image_dsc_t icon_blood_oxygen_t1;
extern const lv_image_dsc_t icon_blood_oxygen_t2;
extern const lv_image_dsc_t icon_blood_oxygen_t3;
extern const lv_image_dsc_t icon_blood_oxygen_t4;

extern const lv_image_dsc_t icon_temp_humidity_t0;
extern const lv_image_dsc_t icon_temp_humidity_t1;
extern const lv_image_dsc_t icon_temp_humidity_t2;
extern const lv_image_dsc_t icon_temp_humidity_t3;
extern const lv_image_dsc_t icon_temp_humidity_t4;

extern const lv_image_dsc_t icon_ai_t0;
extern const lv_image_dsc_t icon_ai_t1;
extern const lv_image_dsc_t icon_ai_t2;
extern const lv_image_dsc_t icon_ai_t3;
extern const lv_image_dsc_t icon_ai_t4;

extern const lv_image_dsc_t icon_mic_t0;
extern const lv_image_dsc_t icon_mic_t1;
extern const lv_image_dsc_t icon_mic_t2;
extern const lv_image_dsc_t icon_mic_t3;
extern const lv_image_dsc_t icon_mic_t4;

#endif /* __AI_WATCH_ICONS_H */
