#!/usr/bin/env python3
"""
Convert 128x128 RGBA PNG icons to ARGB8888 C arrays at multiple tiers.

Tier sizes: 160, 100, 75, 50, 25 pixels.
Input:  src/*.png (128x128 RGBA)
Output: ai_watch_icons.c + ai_watch_icons.h

Usage:
  python3 convert_icons.py

Requirements:
  pip install Pillow
"""

import os
import sys
from PIL import Image

# Tier definitions: (name_suffix, pixel_size)
TIERS = [
    ("t0", 160),
    ("t1", 100),
    ("t2", 75),
    ("t3", 50),
    ("t4", 25),
]

# Icon definitions: (file_stem, c_variable_prefix)
ICONS = [
    ("exercise", "icon_exercise"),
    ("timer", "icon_timer"),
    ("reminder", "icon_reminder"),
    ("settings", "icon_settings"),
    ("heart_rate", "icon_heart_rate"),
    ("blood_oxygen", "icon_blood_oxygen"),
    ("temp_humidity", "icon_temp_humidity"),
]

SRC_DIR = "src"
OUT_C = "ai_watch_icons.c"
OUT_H = "ai_watch_icons.h"


def png_to_argb8888(img_path, size):
    """Load PNG, resize, convert to ARGB8888 bytes."""
    img = Image.open(img_path).convert("RGBA")
    img = img.resize((size, size), Image.LANCZOS)

    pixels = []
    for y in range(size):
        for x in range(size):
            r, g, b, a = img.getpixel((x, y))
            # LVGL ARGB8888: 0xAARRGGBB (little-endian in memory)
            # But LVGL actually uses 0xAARRGGBB packed as bytes: B,G,R,A
            pixels.extend([b, g, r, a])

    return bytes(pixels), size


def generate_c_array(var_name, data, size):
    """Generate C array declaration."""
    lines = []
    lines.append(f"static const LV_ATTRIBUTE_MEM_ALIGN "
                 f"LV_ATTRIBUTE_LARGE_CONST uint8_t {var_name}_map[] =")
    lines.append("{")

    # Format as hex bytes, 16 per line
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        hex_str = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"  {hex_str},")

    lines.append("};")
    lines.append("")
    lines.append(f"const lv_image_dsc_t {var_name} =")
    lines.append("{")

    # Calculate stride: width * 4 bytes per pixel
    stride = size * 4

    lines.append(f"  .header =")
    lines.append(f"  {{")
    lines.append(f"    .cf = LV_COLOR_FORMAT_ARGB8888,")
    lines.append(f"    .w = {size},")
    lines.append(f"    .h = {size},")
    lines.append(f"    .stride = {stride},")
    lines.append(f"  }},")
    lines.append(f"  .data_size = sizeof({var_name}_map),")
    lines.append(f"  .data = {var_name}_map,")

    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    src_dir = os.path.join(script_dir, SRC_DIR)
    out_c = os.path.join(script_dir, OUT_C)
    out_h = os.path.join(script_dir, OUT_H)

    # Check source icons exist
    missing = []
    for stem, _ in ICONS:
        path = os.path.join(src_dir, f"{stem}.png")
        if not os.path.exists(path):
            missing.append(path)

    if missing:
        print(f"ERROR: Missing source icons:")
        for m in missing:
            print(f"  {m}")
        sys.exit(1)

    # Generate .c file
    c_lines = []
    c_lines.append("/* Auto-generated by convert_icons.py — DO NOT EDIT */")
    c_lines.append("")
    c_lines.append('#include <lvgl/lvgl.h>')
    c_lines.append('#include "ai_watch_icons.h"')
    c_lines.append("")

    total_bytes = 0

    for stem, prefix in ICONS:
        path = os.path.join(src_dir, f"{stem}.png")
        for tier_suffix, tier_size in TIERS:
            var_name = f"{prefix}_{tier_suffix}"
            data, size = png_to_argb8888(path, tier_size)
            total_bytes += len(data)
            c_lines.append(f"/* {var_name} — {size}x{size} ARGB8888 "
                           f"({len(data)} bytes) */")
            c_lines.append(generate_c_array(var_name, data, size))

    with open(out_c, "w") as f:
        f.write("\n".join(c_lines))

    # Generate .h file
    h_lines = []
    h_lines.append("/* Auto-generated by convert_icons.py — DO NOT EDIT */")
    h_lines.append("")
    h_lines.append("#ifndef __AI_WATCH_ICONS_H")
    h_lines.append("#define __AI_WATCH_ICONS_H")
    h_lines.append("")
    h_lines.append("#include <lvgl/lvgl.h>")
    h_lines.append("")
    h_lines.append(f"#define AI_WATCH_ICON_TIERS  {len(TIERS)}")
    h_lines.append("")

    for _, prefix in ICONS:
        for tier_suffix, tier_size in TIERS:
            var_name = f"{prefix}_{tier_suffix}"
            h_lines.append(f"extern const lv_image_dsc_t {var_name};")

        h_lines.append("")

    h_lines.append("#endif /* __AI_WATCH_ICONS_H */")
    h_lines.append("")

    with open(out_h, "w") as f:
        f.write("\n".join(h_lines))

    print(f"Generated {OUT_C} and {OUT_H}")
    print(f"Icons: {len(ICONS)}, Tiers: {len(TIERS)}")
    print(f"Total icon data: {total_bytes:,} bytes "
          f"({total_bytes / 1024:.1f} KB)")


if __name__ == "__main__":
    main()
